spring:
  datasource:
    url: jdbc:mysql://mydb-instance.c36ok0iyywfv.us-west-1.rds.amazonaws.com/user_service_db
    username: admin
    password: Aditya87Password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicTypeRegistry: TRACE
server:
  port: 8081